### ISSUE TITLE
怎么以server 模式启动呢

### ISSUE THREAD

**Issue by cyberskycat** [blocktree/openwallet#21]

**Comment by fanyinghao** [comment]
@cyberskycat 这项目是openwallet体系的核心中间件，相关的应用项目包括[go-openw-cli](https://github.com/blocktree/go-openw-cli) 和 [go-openw-sdk](https://github.com/blocktree/go-openw-sdk)

**Comment by fanyinghao** [comment]
每个资产适配器都可以独立运行测试 https://github.com/blocktree?utf8=%E2%9C%93&q=adapter
